# Site settings
title: Innovations in Travel Modeling
author: Elizabeth Sall
credits: 'Site created by Elizabeth Sall, UrbanLabs LLC'
site-image: itm-square.png

# Event Details
event-title: 2020 TRB Innovations in Travel Modeling Conference
event-date: Late Spring/Early Summer 2020
event-location: _[tentatively] Seattle WA 
event-tagline: ''

# Jekyll build settings
markdown: kramdown
permalink: pretty